<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="49966" started-at="2018-08-09T12:44:47Z" finished-at="2018-08-09T12:45:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="49966" started-at="2018-08-09T12:44:47Z" finished-at="2018-08-09T12:45:37Z">
      <class name="TestSuit.TestCasesSignInAcedmia">
        <test-method status="PASS" signature="OpenBrowser()[pri:0, instance:TestSuit.TestCasesSignInAcedmia@5fbdfdcf]" name="OpenBrowser" is-config="true" duration-ms="10110" started-at="2018-08-09T18:14:47Z" finished-at="2018-08-09T18:14:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method status="PASS" signature="LoginWithWrongUsernamePassword()[pri:0, instance:TestSuit.TestCasesSignInAcedmia@5fbdfdcf]" name="LoginWithWrongUsernamePassword" duration-ms="10171" started-at="2018-08-09T18:14:57Z" finished-at="2018-08-09T18:15:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithWrongUsernamePassword -->
        <test-method status="PASS" signature="LoginWithBlankUsernamePassword()[pri:0, instance:TestSuit.TestCasesSignInAcedmia@5fbdfdcf]" name="LoginWithBlankUsernamePassword" duration-ms="6083" started-at="2018-08-09T18:15:07Z" finished-at="2018-08-09T18:15:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithBlankUsernamePassword -->
        <test-method status="PASS" signature="LoginWithBlankUserNameOnly()[pri:0, instance:TestSuit.TestCasesSignInAcedmia@5fbdfdcf]" name="LoginWithBlankUserNameOnly" duration-ms="7576" started-at="2018-08-09T18:15:13Z" finished-at="2018-08-09T18:15:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithBlankUserNameOnly -->
        <test-method status="FAIL" signature="LoginWithBlankPasswordOnly()[pri:0, instance:TestSuit.TestCasesSignInAcedmia@5fbdfdcf]" name="LoginWithBlankPasswordOnly" duration-ms="15988" started-at="2018-08-09T18:15:21Z" finished-at="2018-08-09T18:15:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<1> but was:<0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at TestSuit.TestCasesSignInAcedmia.LoginWithBlankPasswordOnly(TestCasesSignInAcedmia.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithBlankPasswordOnly -->
      </class> <!-- TestSuit.TestCasesSignInAcedmia -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
